/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["v1_auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/patients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Endpoint para listar pacientes.
         *     Implementa busca segura via Blind Indexing no campo criptografado 'full_name'.
         */
        get: operations["v1_core_patients_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/patients/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Endpoint para listar pacientes.
         *     Implementa busca segura via Blind Indexing no campo criptografado 'full_name'.
         */
        get: operations["v1_core_patients_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Perfil do Usuário Logado
         * @description Retorna os dados do usuário autenticado + perfil + papéis.
         */
        get: operations["v1_core_users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        get: operations["v1_social_recipes_list"];
        put?: never;
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        post: operations["v1_social_recipes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/recipes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        get: operations["v1_social_recipes_retrieve"];
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        put: operations["v1_social_recipes_update"];
        post?: never;
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        delete: operations["v1_social_recipes_destroy"];
        options?: never;
        head?: never;
        /** @description Endpoint para o Hub de Receitas Afetivas. */
        patch: operations["v1_social_recipes_partial_update"];
        trace?: never;
    };
    "/api/v1/social/recipes/{id}/like/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Gamificação simples: Curtir uma receita. */
        post: operations["v1_social_recipes_like_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Allergen: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            severity_level?: components["schemas"]["AllergenSeverityEnum"];
            description?: string;
        };
        AllergenRequest: {
            name: string;
            severity_level?: components["schemas"]["AllergenSeverityEnum"];
            description?: string;
        };
        /**
         * @description * `HIGH` - Alto Risco (Anafilaxia Comum)
         *     * `MEDIUM` - Médio (Intolerância Comum)
         *     * `LOW` - Baixo Risco
         * @enum {string}
         */
        AllergenSeverityEnum: "HIGH" | "MEDIUM" | "LOW";
        /**
         * @description * `1` - Nível 1: Dependente (Início)
         *     * `2` - Nível 2: Colaborativo (Intermediário)
         *     * `3` - Nível 3: Autônomo (Mestre)
         * @enum {integer}
         */
        AutonomyLevelEnum: 1 | 2 | 3;
        /** @description (P13) Serializer de Leitura: Dados aninhados e formatados para a UI. */
        FamilyRecipeRead: {
            /** Format: uuid */
            readonly id: string;
            /** Nome da Receita */
            title: string;
            /**
             * Origem
             * @description De onde você conhece? É uma tradição familiar?
             */
            origin_story?: string;
            /**
             * Valor Afetivo
             * @description Quais lembranças positivas traz? Quando costuma fazer?
             */
            emotional_value?: string;
            /** @description Ex: Café da manhã, Almoço de Domingo, Ceia de Natal. */
            consumption_context?: string;
            /**
             * Ingredientes
             * @description Lista completa dos ingredientes e quantidades.
             */
            ingredients_text: string;
            /** Modo de Preparo */
            preparation_method: string;
            /** Porções */
            servings?: number;
            /** Tempo de Preparo (min) */
            preparation_time_minutes?: number | null;
            readonly detected_allergens: components["schemas"]["Allergen"][];
            /** @description JSON estimado pela IA: {kcal, carb, prot, fat, sodium}. */
            nutritional_info_snapshot?: unknown;
            /** @description Lista de avisos da IA: ['Alto Sódio', 'Risco de Engasgo', 'Contém Glúten']. */
            safety_flags?: unknown;
            status?: components["schemas"]["RecipeStatusEnum"];
            readonly status_display: string;
            /** @description Se visível no Hub Global de Receitas. */
            is_public?: boolean;
            likes_count?: number;
            readonly author: components["schemas"]["UserSimple"];
            readonly validated_by: components["schemas"]["ProfessionalSimple"];
            /** Format: date-time */
            readonly created_at_fmt: string;
        };
        /** @description (P13) Serializer de Leitura: Dados aninhados e formatados para a UI. */
        FamilyRecipeReadRequest: {
            /** Nome da Receita */
            title: string;
            /**
             * Origem
             * @description De onde você conhece? É uma tradição familiar?
             */
            origin_story?: string;
            /**
             * Valor Afetivo
             * @description Quais lembranças positivas traz? Quando costuma fazer?
             */
            emotional_value?: string;
            /** @description Ex: Café da manhã, Almoço de Domingo, Ceia de Natal. */
            consumption_context?: string;
            /**
             * Ingredientes
             * @description Lista completa dos ingredientes e quantidades.
             */
            ingredients_text: string;
            /** Modo de Preparo */
            preparation_method: string;
            /** Porções */
            servings?: number;
            /** Tempo de Preparo (min) */
            preparation_time_minutes?: number | null;
            /** @description JSON estimado pela IA: {kcal, carb, prot, fat, sodium}. */
            nutritional_info_snapshot?: unknown;
            /** @description Lista de avisos da IA: ['Alto Sódio', 'Risco de Engasgo', 'Contém Glúten']. */
            safety_flags?: unknown;
            status?: components["schemas"]["RecipeStatusEnum"];
            /** @description Se visível no Hub Global de Receitas. */
            is_public?: boolean;
            likes_count?: number;
        };
        /** @description (P13) Serializer de Escrita: Validação estrita de entrada. */
        FamilyRecipeWrite: {
            /** Nome da Receita */
            title: string;
            /**
             * Origem
             * @description De onde você conhece? É uma tradição familiar?
             */
            origin_story?: string;
            /**
             * Valor Afetivo
             * @description Quais lembranças positivas traz? Quando costuma fazer?
             */
            emotional_value?: string;
            /** @description Ex: Café da manhã, Almoço de Domingo, Ceia de Natal. */
            consumption_context?: string;
            /**
             * Ingredientes
             * @description Lista completa dos ingredientes e quantidades.
             */
            ingredients_text: string;
            /** Modo de Preparo */
            preparation_method: string;
            /** Porções */
            servings?: number;
            /** Tempo de Preparo (min) */
            preparation_time_minutes?: number | null;
            /** @description Se visível no Hub Global de Receitas. */
            is_public?: boolean;
        };
        /** @description (P13) Serializer de Escrita: Validação estrita de entrada. */
        FamilyRecipeWriteRequest: {
            /** Nome da Receita */
            title: string;
            /**
             * Origem
             * @description De onde você conhece? É uma tradição familiar?
             */
            origin_story?: string;
            /**
             * Valor Afetivo
             * @description Quais lembranças positivas traz? Quando costuma fazer?
             */
            emotional_value?: string;
            /** @description Ex: Café da manhã, Almoço de Domingo, Ceia de Natal. */
            consumption_context?: string;
            /**
             * Ingredientes
             * @description Lista completa dos ingredientes e quantidades.
             */
            ingredients_text: string;
            /** Modo de Preparo */
            preparation_method: string;
            /** Porções */
            servings?: number;
            /** Tempo de Preparo (min) */
            preparation_time_minutes?: number | null;
            /** @description Se visível no Hub Global de Receitas. */
            is_public?: boolean;
        };
        /**
         * @description * `PLATFORM` - Plataforma Vitalia
         *     * `CLINIC` - Clínica/Hospital
         *     * `SOLO` - Profissional Liberal
         *     * `ACADEMIC` - Instituição Acadêmica
         *     * `PARTNER` - Parceiro de Marketplace
         * @enum {string}
         */
        OrgTypeEnum: "PLATFORM" | "CLINIC" | "SOLO" | "ACADEMIC" | "PARTNER";
        OrganizationSimple: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            org_type?: components["schemas"]["OrgTypeEnum"];
            /** @description Configurações visuais: cores, logo, terminologia. */
            theme_config?: unknown;
        };
        ParticipantProfile: {
            readonly id: number;
            autonomy_level?: components["schemas"]["AutonomyLevelEnum"];
            personality_type?: components["schemas"]["PersonalityTypeEnum"];
            /** Format: decimal */
            gamification_wallet_balance?: string;
            current_streak_days?: number;
        };
        /** @description (P13) Serializer de Escrita: Validação estrita de entrada. */
        PatchedFamilyRecipeWriteRequest: {
            /** Nome da Receita */
            title?: string;
            /**
             * Origem
             * @description De onde você conhece? É uma tradição familiar?
             */
            origin_story?: string;
            /**
             * Valor Afetivo
             * @description Quais lembranças positivas traz? Quando costuma fazer?
             */
            emotional_value?: string;
            /** @description Ex: Café da manhã, Almoço de Domingo, Ceia de Natal. */
            consumption_context?: string;
            /**
             * Ingredientes
             * @description Lista completa dos ingredientes e quantidades.
             */
            ingredients_text?: string;
            /** Modo de Preparo */
            preparation_method?: string;
            /** Porções */
            servings?: number;
            /** Tempo de Preparo (min) */
            preparation_time_minutes?: number | null;
            /** @description Se visível no Hub Global de Receitas. */
            is_public?: boolean;
        };
        /**
         * @description * `ACHIEVER` - Realizador
         *     * `SOCIALIZER` - Socializador
         *     * `CAUTIOUS` - Cauteloso/Seguro
         *     * `EXPLORER` - Explorador
         *     * `UNKNOWN` - Não Identificado
         * @enum {string}
         */
        PersonalityTypeEnum: "ACHIEVER" | "SOCIALIZER" | "CAUTIOUS" | "EXPLORER" | "UNKNOWN";
        /**
         * @description * `TRAINEE` - Em Treinamento
         *     * `SPECIALIST` - Especialista Certificado
         *     * `AUTHORITY` - Autoridade/Líder
         * @enum {string}
         */
        ProfessionalLevelEnum: "TRAINEE" | "SPECIALIST" | "AUTHORITY";
        ProfessionalProfile: {
            readonly id: number;
            professional_level?: components["schemas"]["ProfessionalLevelEnum"];
            /**
             * Format: double
             * @description Score de 0 a 5 baseado em feedback e auditoria.
             */
            reputation_score?: number;
            /** @description Lista de especialidades (ex: ['Cardiologia', 'Nutrição Esportiva']). */
            specialties?: unknown;
            is_verified?: boolean;
        };
        /** @description Serializer simplificado para exibir quem validou a receita. */
        ProfessionalSimple: {
            readonly id: number;
            readonly name: string;
            professional_level?: components["schemas"]["ProfessionalLevelEnum"];
        };
        /** @description Serializer simplificado para exibir quem validou a receita. */
        ProfessionalSimpleRequest: {
            professional_level?: components["schemas"]["ProfessionalLevelEnum"];
        };
        /**
         * @description * `DRAFT` - Rascunho
         *     * `PENDING_REVIEW` - Aguardando Análise
         *     * `PUBLISHED` - Publicada no Hub
         *     * `FLAGGED` - Sinalizada (Risco de Segurança)
         *     * `ARCHIVED` - Arquivada
         * @enum {string}
         */
        RecipeStatusEnum: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "FLAGGED" | "ARCHIVED";
        Role: {
            name: string;
            description?: string;
            /** @description Papéis de sistema não podem ser deletados (ex: Admin, Participante). */
            is_system_role?: boolean;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        UserProfile: {
            readonly id: number;
            readonly user: components["schemas"]["UserSimple"];
            readonly full_name: string;
            /** Format: uri */
            avatar_url?: string | null;
            readonly roles: components["schemas"]["Role"][];
            readonly primary_organization: components["schemas"]["OrganizationSimple"];
            readonly professional_data: components["schemas"]["ProfessionalProfile"];
            readonly participant_data: components["schemas"]["ParticipantProfile"];
        };
        UserSimple: {
            readonly id: number;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
        };
        UserSimpleRequest: {
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_core_patients_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"][];
                };
            };
        };
    };
    v1_core_patients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este user profile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    v1_core_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    v1_social_recipes_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeRead"][];
                };
            };
        };
    };
    v1_social_recipes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyRecipeWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FamilyRecipeWriteRequest"];
                "multipart/form-data": components["schemas"]["FamilyRecipeWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeWrite"];
                };
            };
        };
    };
    v1_social_recipes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeRead"];
                };
            };
        };
    };
    v1_social_recipes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyRecipeWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FamilyRecipeWriteRequest"];
                "multipart/form-data": components["schemas"]["FamilyRecipeWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeWrite"];
                };
            };
        };
    };
    v1_social_recipes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_social_recipes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFamilyRecipeWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFamilyRecipeWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedFamilyRecipeWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeWrite"];
                };
            };
        };
    };
    v1_social_recipes_like_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyRecipeReadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FamilyRecipeReadRequest"];
                "multipart/form-data": components["schemas"]["FamilyRecipeReadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRecipeRead"];
                };
            };
        };
    };
}
